version: '3.9'

services:
  backend:
    container_name: backend_goku
    build: 
      context: ./api
      dockerfile: Dockerfile
    networks:
      - goku_net
    ports:
      - "9001:8081"

  frontend:
    container_name: frontend_goku
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - backend
    networks:
      - goku_net

networks:
  goku_net:
    driver: bridge